version: "3"
services: 
  springboot-todo:
    image: springboot-todo
    restart: always
    build: .
    ports:
      - 8082:8082
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: shruthi@174
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: todoList
      MYSQL_ROOT_PASSWORD: shruthi@174
        